### ISSUE TITLE
Possible to search through an array?

### ISSUE THREAD

**Issue by made-by-chris** [lykmapipo/mongoose-searchable#2]
Hi there, thanks for this amazing plugin. 
Is it possible to iterate through an array using your library to check for searched words also?
Each document I have contains a 'tags' array with keywords. 
Thanks for your help!
EDIT: 
I reread your documentation, all the answers are there. Thanks!

**Comment by lykmapipo** [comment]
@basiclaser 

Hope it works as you expected.
